Feature/hbd 6568
Handbid/ios_ipad2 pull request #43
Opened 2024-06-12 09:07 UTC by mprzypasniak99

2024-06-16 20:10 UTC, BakJakub requested changes
Tests do not pass and socket for auctions does not work

2024-06-16 20:10 UTC, BakJakub commented on Handbid_iPad/Views/MainContainer/Auction/ItemView.swift
> +			Text(item.currentPrice ?? -1, format: .currency(code: currencyCode))
Why -1, not 0 ?

2024-06-17 13:09 UTC, mprzypasniak99 commented on Handbid_iPad/Views/ChooseOrgAndAuction/Auction/AuctionCollectionCellView.swift
> -			coordinator.push(MainContainerPage.mainContainer as! T)
Changed

2024-06-17 13:10 UTC, mprzypasniak99 commented on Handbid_iPad/Data/WebSocket/Processors/AuctionProcessor.swift
> +			let message = try WebSocketMessageModel<AuctionModel>.decode(data)
work

2024-06-17 13:10 UTC, mprzypasniak99 commented on Handbid_iPad/ViewModels/MainContainer/AuctionViewModel.swift
> +	@Published var currencyCode: String = "USD"
Changed

2024-06-17 13:10 UTC, mprzypasniak99 commented on Handbid_iPad/ViewModels/MainContainer/AuctionViewModel.swift
>  	@Published var auctionStatus = "Open"
Changed

2024-06-17 13:10 UTC, mprzypasniak99 commented on Handbid_iPad/ViewModels/MainContainer/AuctionViewModel.swift
> +		auctionId = auction.identity ?? 0
Changed

2024-06-17 13:12 UTC, mprzypasniak99 commented on Handbid_iPad/Views/MainContainer/Auction/ItemView.swift
> +			Text(item.currentPrice ?? -1, format: .currency(code: currencyCode))
I assume there might be a situation when there are items with price equal to 0. -1 on the other hand won't happen normally and showing price as -1 will make it more visible that there's some issue in the logic/data

2024-06-18 09:32 UTC, merged