Feature/hbd-6684
Handbid/ios_ipad2 pull request #58
Opened 2024-09-12 06:16 UTC by BakJakub

2024-09-13 16:06 UTC, mprzypasniak99 requested changes

2024-09-13 16:06 UTC, mprzypasniak99 commented on Handbid_iPadTests/View_Tests/MainPage/Item/Buttons/BiddingDisabledButtonViewTests.swift
> +		XCTAssertEqual(text, "Online bidding currently disabled for this item")
Should be changed to `XCTAssertEqual(text, String(localized: [...])` after hardcoded strings are moved to spreadsheet

2024-09-13 16:06 UTC, mprzypasniak99 commented on Handbid_iPadTests/View_Tests/MainPage/Item/Buttons/ButtonSectionItemFactoryTests.swift
> +		XCTAssertNoThrow(try view.inspect().find(text: "Item is not open for bidding"))
Should be changed to `XCTAssertNoThrow(try view.inspect().find(text: String(localized: [...])` after hardcoded strings are moved to spreadsheet

2024-09-13 16:06 UTC, mprzypasniak99 commented on Handbid_iPadTests/View_Tests/MainPage/Item/Buttons/ButtonSectionItemFactoryTests.swift
> +		XCTAssertNoThrow(try view.inspect().find(text: "Item has been purchased"))
Should be changed to `XCTAssertNoThrow(try view.inspect().find(text: String(localized: [...])` after hardcoded strings are moved to spreadsheet

2024-09-13 16:06 UTC, mprzypasniak99 commented on Handbid_iPadTests/View_Tests/MainPage/Item/Buttons/NormalSoldButtonViewTests.swift
> +		XCTAssertEqual(try text.string(), "Item has been purchased")
Should be changed to `XCTAssertEqual(try text.string(), String(localized: [...]))` after hardcoded strings are moved to spreadsheet

2024-09-16 21:06 UTC, BakJakub commented on Handbid_iPad/Configuration Appearence/TextStyles.swift
> +	     subheader, accentBody, leadingLabel, titleLeading, itemDetailValue, itemDetailDescription
Right, I forgot to delete that

2024-09-16 21:18 UTC, BakJakub commented on Handbid_iPad/ViewModels/MainContainer/Item/PerformTransactionRepository.swift
> +protocol PerformTransactionRepository {
I suggest staying with PerformTransactionRepository and adding only Protoocol at the end. My idea here is to expand this later depending on what type of transaction is performed. I have only added bid but in the future I would like to add buy etc here as well. What do you think about making the methods optional and using them according to later needs? I don't think it is worth breaking up places like this into even smaller parts and separate buy, bid, etc.

2024-09-16 21:21 UTC, BakJakub commented on Handbid_iPad/ViewModels/MainContainer/AuctionViewModel.swift
> +	init(dataService: DataServiceWrapper, repository: AuctionRepository, repositoryPerformTransaction: PerformTransactionRepository? = nil) {
It seems to me that this allows for better customisation and also makes it easier for us to test

2024-09-16 21:22 UTC, BakJakub commented on Handbid_iPad/ViewModels/MainContainer/AuctionViewModel.swift
> +	init(dataService: DataServiceWrapper, repository: AuctionRepository, repositoryPerformTransaction: PerformTransactionRepository? = nil) {
It seems to me that this allows for better customisation and also makes it easier for us to test

2024-09-16 21:23 UTC, BakJakub commented on Handbid_iPad/ViewModels/MainContainer/AuctionViewModel.swift
> +		currencyCode = auction.currencyCode ?? ""
The lack of currency will not cause an error, it will only inform us that the backend is not working properly

2024-09-16 21:24 UTC, BakJakub commented on Handbid_iPad/ViewModels/MainContainer/Item/PerformTransactionRepository.swift
Yes, I agree with you

2024-09-17 08:53 UTC, mprzypasniak99 commented on Handbid_iPad/ViewModels/MainContainer/AuctionViewModel.swift
> +	init(dataService: DataServiceWrapper, repository: AuctionRepository, repositoryPerformTransaction: PerformTransactionRepository? = nil) {
`AuctionRepository` is not optional. Please change `respositoryPerformTransaction`'s type from `PerformTransactionRepository?` to `PerformTransactionRepository`. 

There's no need for it to be optional here

2024-09-17 09:52 UTC, mprzypasniak99 commented on Handbid_iPad/ViewModels/MainContainer/Item/PerformTransactionRepository.swift
> +protocol PerformTransactionRepository {
I don't mean breaking it into smaller files or classes. I just meant that the name may be confusing since all we do here is create bids/purchases in the system. No transactions are involved, and even if we add new endpoints, they probably won't involve anything different than creating bids/purchases. Transaction is something completely different than bids/purchases in the system and I want to avoid causing unnecessary confusion with naming of classes

2024-09-17 18:46 UTC, BakJakub commented on Handbid_iPad/Data/WebSocket/WebSocketManager.swift
> +		ProcessorRegistry.shared.registerProcessor(ItemProcessor(), for: .auction)
Right

2024-09-18 09:20 UTC, mprzypasniak99 requested changes

2024-09-18 09:20 UTC, mprzypasniak99 commented on Handbid_iPad/ViewModels/MainContainer/Item/ItemDetailViewModel.swift
> +	// let repositoryPerformTransaction: PerformTransactionRepository
Why is it commented out?

2024-09-18 09:20 UTC, mprzypasniak99 commented on Handbid_iPad/Views/MainContainer/Item/ImageGalleryView.swift
> +						Text(item.isLive ?? false ? "LIVE" : "FOR SALE")
Move to [spreadsheet](https://docs.google.com/spreadsheets/d/1krgwQDoMYx2tS4G9K-1QyMd5ogKlqh4kcWQXBnPOcDI/edit?gid=401431233#gid=401431233)

Also, instead of having text in uppercase, add .textCase(.uppercase) modifier to the Text view

2024-09-20 09:31 UTC, BakJakub commented on Handbid_iPad/ViewModels/MainContainer/Item/ItemDetailViewModel.swift
> +	// let repositoryPerformTransaction: PerformTransactionRepository
I have changed the way the bid is created

2024-09-20 09:32 UTC, BakJakub commented on Handbid_iPad/Data/WebSocket/WebSocketManager.swift
> +		ProcessorRegistry.shared.registerProcessor(ItemProcessor(), for: .quantityThreshold)
Changed

2024-09-20 09:32 UTC, BakJakub commented on Handbid_iPadTests/View_Tests/MainPage/Item/Buttons/NormalSoldButtonViewTests.swift
> +		XCTAssertEqual(try text.string(), "Item has been purchased")
Right, changed

2024-09-20 10:03 UTC, BakJakub commented on Handbid_iPad/Views/MainContainer/Item/ImageGalleryView.swift
> +						Text(item.isLive ?? false ? "LIVE" : "FOR SALE")
Updated

2024-09-20 11:59 UTC, BakJakub commented on Handbid_iPadTests/ViewModel_Tests/MainPage/AuctionViewModelTests.swift
Fixed

2024-09-20 11:59 UTC, BakJakub commented on Handbid_iPadTests/View_Tests/MainPage/Item/Buttons/ButtonSectionItemFactoryTests.swift
> +		XCTAssertNoThrow(try view.inspect().find(text: "Item is not open for bidding"))
Changed

2024-09-20 11:59 UTC, BakJakub commented on Handbid_iPadTests/View_Tests/MainPage/Item/Buttons/NormalSoldButtonViewTests.swift
> +		XCTAssertEqual(try text.string(), "Item has been purchased")
Chamged

2024-09-20 12:00 UTC, BakJakub commented on Handbid_iPadTests/View_Tests/MainPage/Item/Buttons/ButtonSectionItemFactoryTests.swift
> +		XCTAssertNoThrow(try view.inspect().find(text: "Item has been purchased"))
Changed

2024-09-20 12:00 UTC, BakJakub commented on Handbid_iPadTests/View_Tests/MainPage/Item/Buttons/BiddingDisabledButtonViewTests.swift
> +		XCTAssertEqual(text, "Online bidding currently disabled for this item")
Changed

2024-09-20 12:00 UTC, BakJakub commented on Handbid_iPad/Data/WebSocket/WebSocketManager.swift
> +		ProcessorRegistry.shared.registerProcessor(ItemProcessor(), for: .quantityThreshold)
Changed

2024-09-20 12:24 UTC, merged